os: osx
language: swift
osx_image: xcode11.2
script:
    - xcodebuild clean test -project CurrencyConverter.xcodeproj -scheme CurrencyConverter -destination "platform=iOS Simulator,name=iPhone 11,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet

