name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: xcodebuild clean test -project 'CurrencyConverter.xcodeproj' -scheme 'CurrencyConverter' -destination "platform=iOS Simulator,name=iPhone 11,OS=latest"
    - name: Buld App
      run: xcodebuild -project 'CurrencyConverter.xcodeproj' -scheme 'CurrencyConverter' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO
